[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "web/dist"

[functions]
  node_bundler = "esbuild"

[functions.progress]
  included_files = ["img/**"]

[[redirects]]
  from = "/progress"
  to = "/.netlify/functions/progress"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200